### ISSUE TITLE
Add the ability to set the build directory

### ISSUE THREAD

**Issue by as71xoho** [spaceagetv/electron-playwright-helpers#2]
The "findLatesBuild" function does currently only account for projects with a build folder named "out". It would be nice to have a parameter to change this directory (e.g. "build")

**Comment by as71xoho** [comment]
#3

**Comment by andirsun** [comment]
@as71xoho Thanks for your help with the PR seems like @jjeff  is going to help here.

**Comment by jjeff** [comment]
closed with #3
