### ISSUE TITLE
installing causes an error since 1.3.0

### ISSUE THREAD

**Issue by omnidan** [spaceagetv/electron-playwright-helpers#22]
I noticed that after upgrading to 1.3.1, I am getting the following error when installing the package:

```
# This file contains the result of Yarn building a package (electron-playwright-helpers@npm:1.3.1)
# Script name: postinstall

cd: no such file or directory: example-project
```

I looked it up and it seems to be due to a recent change, the following line was added:

```
    "postinstall": "cd example-project && npm install",
```

But in the distributed npm package, `example-project` is not included. I think the `postinstall` script needs to be adjusted, as it will run when installing the distributed npm package as well.

**Comment by jjeff** [comment]
Just posted 1.4 which removes this line. I'll close this issue, but let me know if you're still havening the problem with the new version.

**Comment by omnidan** [comment]
Thanks for the quick response @jjeff! It works fine now 😁
