### ISSUE TITLE
findLatestBuild: doesn't accept absolute path on Windows

### ISSUE THREAD

**Issue by MatthijsBurgh** [spaceagetv/electron-playwright-helpers#30]
Windows paths don't start with a `/`. So the following check is invalid for windows:
https://github.com/spaceagetv/electron-playwright-helpers/blob/03203fd7eabd79c69f35e85dcb9c08c819e9fa5c/src/find_parse_builds.ts#L27-L29

**Comment by jjeff** [comment]
closed via #31
