### ISSUE TITLE
Electron 25 compatibility

### ISSUE THREAD

**Issue by MatthijsBurgh** [spaceagetv/electron-playwright-helpers#38]
I am getting errors when using the helpers in combination with EPH.

`ipcMainInvokeHandler` does not seem to be working anymore for me. (See: https://github.com/MatthijsBurgh/vue-cli-plugin-electron-builder/actions/runs/5118894543/jobs/9203457814?pr=65#step:8:185)

Could you please trigger dependabot to create a PR to update electron in this project. To check whether the tests in this project keep succeeding or fail.

**Comment by jjeff** [comment]
It looks like the tests from your PR are failing with Electron 25.

I was afraid that Electron might break [ipcMainInvokeHandler](https://github.com/spaceagetv/electron-playwright-helpers/blob/eaf4c2a3d1c1ce7cd8ec9f57062c2ab37050c8ac/src/ipc_helpers.ts#L236-L265). There's even a comment in the code that documents the hack. I (or you?) need to look at what changed in Electron 25's implementation of `ipcMain.handle()` and figure out if we can still get in there and find the registered handlers.

**Comment by jjeff** [comment]
IIRC, this is the file that handles ipcMain.handle(): 
https://github.com/electron/electron/blob/25-x-y/lib/browser/ipc-main-impl.ts

There was a change recently to "simplify events". Maybe that's what broke it?
