### ISSUE TITLE
Feature request: allow interacting with menus other than application menu

### ISSUE THREAD

**Issue by mstykow** [spaceagetv/electron-playwright-helpers#45]
As stated in the documentation, it is currently only possible to click on menu items that are part of the application menu.

As a user of this library, I would like to also click on menu items in other menus.

The `findMenuItem` method already detects _all_ menu items. So perhaps it's not too difficult to also create the ability to interact with those items?

Great library!

**Comment by mstykow** [comment]
Never mind, I think i misunderstood the limitation. I can in fact interact with all menu items defined as part of the application menu. Perhaps I'm not sure then what you mean by "All menu testing functions will only work with items in the application menu." What would be an example of a menu item outside of the application menu?

**Comment by jjeff** [comment]
Electron allows you to assign separate menus per window (on Windows)… and then there's context (popup) menus as well as the [Tray](https://www.electronjs.org/docs/latest/tutorial/tray) functionality. None of these are accessible directly with this library.

However, it's certainly possible to create ipc handlers in the main process to pop them up and return their contents so you can access them in Playwright. But as far as the conventional menu system, this library should give you access to all of it.

**Comment by mstykow** [comment]
Thank you for the super fast answer. 🚀
