### ISSUE TITLE
out directory not found

### ISSUE THREAD

**Issue by seddik-st** [spaceagetv/electron-playwright-helpers#5]
i'm using findLatestBuild to get app info of theia-electron however an error is thrown because out directory is not found. Any idea ?

**Comment by jjeff** [comment]
I don't quite understand your question. Are you trying to test a distributed application? Or one that you are creating yourself?  If you already know the path to the app, you can just use `parseElectronApp()`.

I recently committed a pull-request to allow a directory argument for `findLatestBuild()`. This should show up on npmjs.com in the next day or two. Is this what you need?

**Comment by seddik11** [comment]
exactly, because my app is not built in "out" directory. so adding it as argument would be very helpful. Thank you
