### ISSUE TITLE
`electron.launch: Failed to launch: Error: spawn /out/MyApp-linux-x64/myapp`

### ISSUE THREAD

**Issue by eliw00d** [spaceagetv/electron-playwright-helpers#7]
I get the following error using the provided example:
```
electron.launch: Failed to launch: Error: spawn /out/MyApp-linux-x64/myapp
```
I checked out the actual file and it is ` /out/MyApp-linux-x64/MyApp`, so it seems to be a matter of casing. 

Any thoughts?

**Comment by rtu** [comment]
@eliw00d , I have a project to use electron-playwright-helpers plus cucumber.js.
I also got a similar error under Ubunutu 20.04.5:
``

**Comment by jjeff** [comment]
I've never had a chance to test this library on Linux. So it was a bit of a shot in the dark as to the executable name on Linux.

So to be clear on the bug: Would it be more accurate to say: "Linux executable path comes back lowercase"?

**Comment by eliw00d** [comment]
@jjeff That is correct. I forgot to post my workaround:

```typescript
      executablePath: appInfo.executable.replace(/gallerydesktop$/, 'GalleryDesktop'),
```
