### ISSUE TITLE
Wait for IPC message

### ISSUE THREAD

**Issue by 2xAA** [spaceagetv/electron-playwright-helpers#8]
Hi,

I'm wondering if it's possible to wait for an IPC message sent from renderer to main?
We have a message that's part of our application lifecycle to know when we've loaded our required assets:

https://github.com/vcync/modV/blob/5f667ffa8d7884a587c34f00088936920d0ef74c/src/application/index.js#L86
https://github.com/vcync/modV/blob/f6674e2b5d05a2568b52623275b22a388b53e4ee/src/background/window-prefs.js#L101

So it would be great to start the tests once we've received that message.

Thanks.

**Comment by jjeff** [comment]
The `ipcRendererSend()` function does return a Promise. So you should be able to wait for it. However, Electron's `ipcRenderer.send()` itself returns a non-Promise void value...

If you wanted to wait for a response from the main process, you'd probably want to use `ipcRendererInvoke()` instead, which sends a message to an `ipcMain.handle()` function and waits for the main process to respond.

**Comment by jjeff** [comment]
Closing this as resolved. Let me know if further information is needed.

**Comment by 2xAA** [comment]
@jjeff Thanks for the reply - sorted this out with `ipcRendererInvoke()` and `ipcMain.handle()` as suggested.

Cheers!
